In [ ]:
import gdal
import ogr

In [ ]:
dataset = gdal.Open('/content/b2.tif')

In [ ]:
print (dataset)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f227ce23660> >


In [ ]:
print ('Количество столбцов в растре:')
print (dataset.RasterXSize)

print ('\nКоличество строк в растре:')
print (dataset.RasterYSize)

print ('\nКоличество каналов ("слоёв в матрице"):')
print (dataset.RasterCount)

Количество столбцов в растре:
750

Количество строк в растре:
539

Количество каналов ("слоёв в матрице"):
1


In [ ]:
print ('Информация о системе координат:')
print (dataset.GetProjection())

print ('\nИнформация о геопривязке:')
print (dataset.GetGeoTransform())

Информация о системе координат:
PROJCS["WGS 84 / UTM zone 20N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-63],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32620"]]

Информация о геопривязке:
(457845.0, 30.0, 0.0, -1909245.0, 0.0, -30.0)


1) 457845.0 - координата X левого верхнего угла растра

2) 30.0 - размер/шаг одного пикселя по X

3) 0.0 - первый поворотный коэффициент 1 (в 99.99% случаев это 0)

4) -1909245.0 - координата Y левого верхнего угла растра

5) 0.0 - второй поворотный коэффициент 1 (в 99.99% случаев это 0)

6) -30.0 - размер/шаг одного пикселя по Y

In [ ]:
#доступ к самим данным
band_1 = dataset.GetRasterBand(1)
print (band_1)

<osgeo.gdal.Band; proxy of <Swig Object of type 'GDALRasterBandShadow *' at 0x7f2297a2f690> >


In [ ]:
# Читаем значения матрицы
band_1_data = band_1.ReadAsArray()
print (band_1_data)

[[ 8949  8805  9094 ...  9160  9199  9180]
 [ 8752  8715  8849 ...  9161  9186  9240]
 [ 8680  8750  8790 ...  9128  9174  9270]
 ...
 [10939 11152 11776 ...  9092  9135  9265]
 [11224 11863 12554 ...  9125  9165  9233]
 [11756 12722 12250 ...  9127  9048  9362]]


In [ ]:
# что лежит в ячейке 100, 100 ?
band_1_data[100,100]

8973

In [ ]:
# Срез по ячейкам - 70 столбец с 50 по 80 строки
band_1_data[50:80, 70]

array([8897, 8902, 8887, 8893, 8927, 8975, 8967, 8945, 8945, 8927, 8891,
       8955, 8960, 8941, 8886, 8802, 8796, 8833, 8861, 8910, 8930, 8921,
       8918, 8913, 8912, 8912, 8908, 8923, 8935, 8928], dtype=uint16)

In [ ]:
# это матрица numpy array. Для работы с ней импортируем numpy
import numpy

In [ ]:
# статистика с помощью numpy
print ('Минимимальное значение:')
print (numpy.nanmin(band_1_data))

print ('\nМаксимальное значение:')
print (numpy.nanmax(band_1_data))

print ('\nСреднее значение:')
print (numpy.nanmean(band_1_data))

Минимимальное значение:
8542

Максимальное значение:
20799

Среднее значение:
9311.382303030303


Работа с векторными данными

In [ ]:
countries = ogr.Open('/content/110/ne_110m_admin_0_countries.shp')

In [ ]:
# смотрим - что это
print (countries)

<osgeo.ogr.DataSource; proxy of <Swig Object of type 'OGRDataSourceShadow *' at 0x7fc68852c7e0> >


In [ ]:
# посмотрим некоторые свойства
print ('Количество слоёв в наборе')
print (countries.GetLayerCount())

Количество слоёв в наборе
1


In [ ]:
# смотрим - что это
print (countries)

<osgeo.ogr.DataSource; proxy of <Swig Object of type 'OGRDataSourceShadow *' at 0x7fc68852c7e0> >


In [ ]:
countries_layer = countries.GetLayerByIndex(0)

# изучим, что это за класс
print(countries_layer)

<osgeo.ogr.Layer; proxy of <Swig Object of type 'OGRLayerShadow *' at 0x7fc6718dc120> >


In [ ]:
# продолжаем извлекать свойства
print ('Название слоя')
print (countries_layer.GetName())

print ('\nТип его геометрии')
print (countries_layer.GetGeomType())

# 1 - точки
# 2 - линии
# 3 - полигоны
# 4 - мультиточки
# 5 - мультилинии
# 6 - мультиполигоны

Название слоя
ne_110m_admin_0_countries

Тип его геометрии
3


In [ ]:
# Теперь смотрим на атрибуты

print ('\nСписок атрибутов и их типы:')

layer_definition = countries_layer.GetLayerDefn()
#print (layer_definition)
for field in range(layer_definition.GetFieldCount()):
    #print (field)
    field_definition = layer_definition.GetFieldDefn(field)
    print ('%s (%s)' % (field_definition.name, field_definition.type))


Список атрибутов и их типы:
featurecla (4)
scalerank (0)
LABELRANK (0)
SOVEREIGNT (4)
SOV_A3 (4)
ADM0_DIF (0)
LEVEL (0)
TYPE (4)
ADMIN (4)
ADM0_A3 (4)
GEOU_DIF (0)
GEOUNIT (4)
GU_A3 (4)
SU_DIF (0)
SUBUNIT (4)
SU_A3 (4)
BRK_DIFF (0)
NAME (4)
NAME_LONG (4)
BRK_A3 (4)
BRK_NAME (4)
BRK_GROUP (4)
ABBREV (4)
POSTAL (4)
FORMAL_EN (4)
FORMAL_FR (4)
NAME_CIAWF (4)
NOTE_ADM0 (4)
NOTE_BRK (4)
NAME_SORT (4)
NAME_ALT (4)
MAPCOLOR7 (0)
MAPCOLOR8 (0)
MAPCOLOR9 (0)
MAPCOLOR13 (0)
POP_EST (12)
POP_RANK (0)
GDP_MD_EST (2)
POP_YEAR (0)
LASTCENSUS (0)
GDP_YEAR (0)
ECONOMY (4)
INCOME_GRP (4)
WIKIPEDIA (0)
FIPS_10_ (4)
ISO_A2 (4)
ISO_A3 (4)
ISO_A3_EH (4)
ISO_N3 (4)
UN_A3 (4)
WB_A2 (4)
WB_A3 (4)
WOE_ID (0)
WOE_ID_EH (0)
WOE_NOTE (4)
ADM0_A3_IS (4)
ADM0_A3_US (4)
ADM0_A3_UN (0)
ADM0_A3_WB (0)
CONTINENT (4)
REGION_UN (4)
SUBREGION (4)
REGION_WB (4)
NAME_LEN (0)
LONG_LEN (0)
ABBREV_LEN (0)
TINY (0)
HOMEPART (0)
MIN_ZOOM (2)
MIN_LABEL (2)
MAX_LABEL (2)
NE_ID (12)
WIKIDATAID (4)
NAME_AR (4)
NAME_BN (4)
NAME_DE (

In [ ]:
# Переходим к объектам
# Можно брать объект по номеру
feature3 = countries_layer.GetFeature(3)
print (feature3)

<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc68ce83600> >


In [ ]:
# либо перебирать их
for feature in countries_layer:
    # перебираем по очереди все объекты
    print (feature)

<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc671b52f00> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc68852c6f0> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc671b52f00> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc68852c3c0> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc671b52f00> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc68852c6f0> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc671b52f00> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc68852c3c0> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc671b52cc0> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc68852c6f0> >
<osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7fc6

In [ ]:
# Получаем свойства отдельного объекта
print ('Геометрия объекта:')
print (feature3.geometry())

Геометрия объекта:
MULTIPOLYGON (((-122.84 49.0,-122.97421 49.0025377777778,-124.91024 49.98456,-125.62461 50.41656,-127.43561 50.83061,-127.99276 51.71583,-127.85032 52.32961,-129.12979 52.75538,-129.30523 53.56159,-130.51497 54.28757,-130.536108952737 54.8027544767992,-130.53611 54.80278,-129.98 55.285,-130.00778 55.91583,-131.70781 56.55212,-132.73042 57.69289,-133.35556 58.41028,-134.27111 58.86111,-134.945 59.27056,-135.47583 59.78778,-136.47972 59.46389,-137.4525 58.905,-138.34089 59.56211,-139.039 60.0,-140.013 60.27682,-140.99778 60.30639,-140.9925 66.00003,-140.986 69.712,-140.985987610376 69.7119983995264,-139.12052 69.47102,-137.54636 68.99002,-136.50358 68.89804,-135.62576 69.31512,-134.41464 69.62743,-132.92925 69.50534,-131.43136 69.94451,-129.79471 70.19369,-129.10773 69.77927,-128.36156 70.01286,-128.13817 70.48384,-127.44712 70.37721,-125.75632 69.48058,-124.42483 70.1584,-124.28968 69.39969,-123.06108 69.56372,-122.6835 69.85553,-121.47226 69.79778,-119.94288 69.37786

In [ ]:
print ('Примеры производных от геометрии')

print ('\nПлощадь:')
print (feature3.geometry().Area())

print ('\nЦентральная точка:')
print (feature3.geometry().Centroid())

Примеры производных от геометрии

Площадь:
1712.9952276493761

Центральная точка:
POINT (-98.142381372097 61.4690761453489)


In [ ]:
# Получаем значение конкретного атрибута

print ('Название страны')
print (feature3['NAME'])

print ('\nЧисленность населения')
print (feature3['POP_EST'])

Название страны
Canada

Численность населения
35623680


In [ ]:
# Все страны с типом экономики 6. Developing region 

for feature in countries_layer:
    if feature['ECONOMY'] == '1. Developing region':
        print ('%s: %s' % (feature['NAME'], feature.geometry().Area()))